input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^{.*}$/ {
    json {
      source => "message"
      target => "parsed_json"
    }
    
    # Extract fields from the parsed JSON
    mutate {
      add_field => {
        "incident_id" => "%{[parsed_json][id]}"
        "title" => "%{[parsed_json][title]}"
        "incident_type" => "%{[parsed_json][type]}"
        "severity" => "%{[parsed_json][severity]}"
        "sector" => "%{[parsed_json][sector]}"
        "source_api" => "%{[parsed_json][source]}"
        "incident_timestamp" => "%{[parsed_json][timestamp]}"
      }
    }
    
    # Remove the wrapper objects to keep it flat and clean
    mutate {
      remove_field => ["message", "parsed_json", "agent", "ecs", "host", "log", "input", "tags"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cyber-incidents-%{+YYYY.MM.dd}"
    ilm_enabled => true
    ilm_policy => "cyber_logs_policy"
    ilm_rollover_alias => "cyber-incidents"
  }
  stdout { codec => rubydebug }
}
